name: Airflow DAG CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - src/**
      - tests/**
      - .github/workflows/ci.yml
  push:
    branches: [ "main", "dev" ]
    paths:
      - src/**
      - tests/**
      - .github/workflows/ci.yml

jobs:
  detect-dag-changes:
    runs-on: ubuntu-latest
    outputs:
      dags_changed: ${{ steps.filter.outputs.dags }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            dags:
              - "src/dags/**"
              - "src/plugins/common/**"
              - "tests/dags/**"
              - "pyproject.toml"

  airflow-ci:
    needs: detect-dag-changes
    # if: needs.detect-dag-changes.outputs.dags_changed == 'true'
    runs-on: ubuntu-latest

    env:
      # Airflow 기본 설정
      AIRFLOW_HOME: ${{ github.workspace }}/airflow
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__UNIT_TEST_MODE: "True"
      AIRFLOW__CORE__DAGS_FOLDER: ${{ github.workspace }}/src/dags

      # DB / 보안
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////${{ github.workspace }}/airflow/airflow.db

      # Python import path
      PYTHONPATH: ${{ github.workspace }}/src:${{ github.workspace }}/src/plugins
    

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # AIRFLOW__CORE__FERNET_KEY load
      - name: Load env from .env.local
        run: |
          if [ -f .env.local ]; then
            grep -v '^#' .env.local | grep -v '^$' >> $GITHUB_ENV
          fi

      # uv 설치
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      # Python 설치
      - name: Install Python 3.12
        run: uv python install 3.12

      # pyproject 환경 sync
      - name: Sync dependencies (dev 포함)
        run: uv sync --dev

      # debug용 path import 확인
      - name: Debug sys.path
        run: |
          uv run python - <<EOF
          import sys
          print("\n".join(sys.path))
          EOF

      # plugins/** editable install
      - name: Install project code (editable)
        run: uv pip install -e .

      # Airflow DB 초기화
      - name: Init Airflow DB
        run: |
          mkdir -p "$AIRFLOW_HOME"
          uv run airflow db migrate

      # CI용 Airflow Variables
      - name: Set dummy Airflow variables
        run: |
          uv run airflow variables set ENV ci
          uv run airflow variables set DUMMY test

      # Ruff (DAG, plugin lint)
      - name: Ruff (DAG only)
        run: uv run ruff check src/dags src/plugins

      # Airflow DAG import test
      - name: Airflow DAG import check
        run: uv run airflow dags list > /dev/null

      # Pytest DAG tests
      - name: Pytest DAG tests
        run: uv run pytest tests/dags -v
